apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-app-config
data:
  application.yaml: |
    spring:
      data:
        mongodb:
          host: mongodb
          port: 27017
          username: ${MONGO_DB_USERNAME}
          password: ${MONGO_DB_PASSWORD}
          database: users
          authentication-database: admin
    server:
      port: 8080
